Release of React Native Themis
cossacklabs/themis pull request #908
Opened 2022-04-05 14:35 UTC by radetsky

- Added React Native Themis 
- Typescript support
- Fixes and improves.

2022-04-05 14:52 UTC, ilammy approved these changes
While I don't think the up-to-date examples are needed on this branch, they don't hurt either.

2022-04-05 20:56 UTC, vixentael requested changes

2022-04-05 20:56 UTC, vixentael commented on CHANGELOG.md
> +## [0.14.4](https://github.com/cossacklabs/themis/releases/tag/0.14.4), April 05th 2022
```suggestion
## [0.14.4](https://github.com/cossacklabs/themis/releases/tag/0.14.4), March 15th 2022 / April 05th 2022
```

2022-04-05 20:56 UTC, vixentael commented on CHANGELOG.md
> +**React Native Support**
Let's keep both dates.

2022-04-06 09:32 UTC, ilammy approved these changes

2022-04-06 11:52 UTC, vixentael approved these changes

2022-04-06 11:53 UTC, merged